# Script to build an emulator for L23 + NMF decomposition
# kubectl exec -it test-pod -- /bin/bash
apiVersion: batch/v1
kind: Job
metadata:
  name: xavier-ihop-emulator-l23-nmf
spec:
  backoffLimit: 0
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - k8s-chase-ci-01.noc.ucsb.edu
              - key: nvidia.com/gpu.product
                operator: In
                values:
                  - NVIDIA-GeForce-RTX-3090
      containers:
      - name: container
        image: localhost:30081/profxj/ihop_nvidia:latest  # UPDATE
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"   # Using at least 4
            memory: "16Gi"  # Using ~7
            ephemeral-storage: 100Gi
          limits:
            cpu: "4"
            memory: "50Gi"
            ephemeral-storage: 150Gi
            nvidia.com/gpu:  "1"  # See docs to exlude certain types
        command: ["/bin/bash", "-c"]
            #command: ["sh", "-c", "sleep infinity"]
        args:
          - cd ocean-color; 
            git fetch;
            git checkout support_ihop; 
            git pull; 
            pip install -e ".[dev]";
            cd ../cnmf;
            git fetch;
            git checkout paper; 
            git pull; 
            pip install -e ".[dev]";
            cd ../ihop;
            git fetch;
            git checkout phase0; 
            git pull; 
            pip install -e ".[dev]";
            aws --endpoint https://s3-west.nrp-nautilus.io s3 cp s3://ihop/IOPs/nmf_L23_X4Y0_a_N03.npz ./ihop/data/NMF/;
            aws --endpoint https://s3-west.nrp-nautilus.io s3 cp s3://ihop/IOPs/nmf_L23_X4Y0_bb_N03.npz ./ihop/data/NMF/;
            cd build/emulators;
            python py/loisel23.py 2;
        env:
          - name: "ENDPOINT_URL"
            value: "http://rook-ceph-rgw-nautiluss3.rook"
          - name: "S3_ENDPOINT"
            value: "rook-ceph-rgw-nautiluss3.rook"
        volumeMounts:
          - name: prp-s3-credentials
            mountPath: "/root/.aws/credentials"
            subPath: "credentials"
          - name: ephemeral
            mountPath: "/tmp"
          - name: "dshm"
            mountPath: "/dev/shm"
      nodeSelector:
        nautilus.io/disktype: nvme
      restartPolicy: Never
      volumes:
        # Secrets file for nautilus s3 credentials .aws/credentials and .s3cfg
        - name: prp-s3-credentials
          secret:
            secretName: prp-s3-credentials
        # Shared memory (necessary for Python's multiprocessing.shared_memory module to work)
        - name: dshm
          emptyDir:
            medium: Memory
        # Ephemeral storage
        - name: ephemeral
          emptyDir: {}
